### PR TITLE
Scanline Menu for SGX

### PR DESCRIPTION
**Pull request by Tatsuya79**
Please check if OK.
Working fine here.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
I see the last change I made in mednafen vdc.cpp got added there. That's probably something you don't want.
I'm not used to those pull requests, I didn't think it would end here. Kill it if you wish.

**Comment by twinaphex** [comment]
Are these changes you made in vdc.cpp backports of newer Mednafen versions? Do they cause any active harm? If they don't then it's fine I think.

**Comment by Tatsuya79** [comment]
Changes in vdc.cpp are not backports.

They are inspired from the PCE "not fast" code to display 352 pixels width instead of 341. (ideally this should be with a core option "horizontal overscan ON/OFF)

In addition there is a fix to display 242 vertical lines ( the "242 + 1" in the code, to regain that line lost somewhere). That's an issue in Mednafen original code, I wrote about it on their forum but got no answer.

**Comment by twinaphex** [comment]
OK, if you can turn that option to display 352 pixels into a core option, then I think we can safely merge that.

**Comment by Tatsuya79** [comment]
That's the problem, I don't know how to code that, I'm really at a beginner level.

It would need to change those values in vdc.cpp from 341 to 352 and activate the 
```
if(vce.dot_clock == 1)
	end += 6;
	start += 6;
```
when 352 is ON.

**Comment by twinaphex** [comment]
Alright, I could look at this for you.

**Comment by Tatsuya79** [comment]
Someone from the Mednafen team says he'll probably make an horizontal overscan switch option:
http://forum.fobby.net/index.php?t=msg&th=1307&#msg_4347

**Comment by Tatsuya79** [comment]
Closing this one that got deprecated.

**Pull request closed without merging**
